In [57]:
#Dia 30 librería Numpy
import numpy as np

In [58]:
#Crear arrays 
# a partir de una lista
vector=np.array([1,2,3,4,5,6,7,8,9])
vector


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(vector)

numpy.ndarray

In [6]:
# a partir de una tupla
vector=np.array(["a","b","c"])
vector


array(['a', 'b', 'c'], dtype='<U1')

In [8]:
# a partir de unconjunto
vector=np.array({1,2,3,4,5,6,7,8,9})
vector

array({1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

In [12]:
#con arrange
vector = np.arange(3, 10, 2)
vector


array([3, 5, 7, 9])

In [14]:
#rellenandocon 0 y 1
vector =np.zeros(7)
vector

array([0., 0., 0., 0., 0., 0., 0.])

In [17]:
vector = np.ones(4)
vector

array([1., 1., 1., 1.])

In [19]:
#con la funcion linspace()
# 5 valores entre uno y 10 repartidos con la misma distancia
vector = np. linspace(1,10,5)
vector



array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
#con la funcion linspace()
#5 valores entre  y 10 repartidos con la misma distancia
vector = np. linspace(0,100,5)
vector

array([  0.,  25.,  50.,  75., 100.])

In [27]:
#mezclando valores de tipos distintos
vector = np.array([1,2,3,4,5])
type(vector)
vector

array([1, 2, 3, 4, 5])

In [28]:
#al poner el 3.0 los convierte todos en flotante
vector = np.array([1,2,3.0,4,5])
type(vector)
vector

array([1., 2., 3., 4., 5.])

In [30]:
#al poner el false pone 0 que es el vlaorpor defecto de false
vector = np.array([1,2,4,5, False])
type(vector)
vector

array([1, 2, 4, 5, 0])

In [37]:
vector = np.array([1,2,4,1.05,5, False])

vector

array([1.  , 2.  , 4.  , 1.05, 5.  , 0.  ])

In [39]:
vector = np.array([1,2,4,5,"Hola"])
vector

array(['1', '2', '4', '5', 'Hola'], dtype='<U11')

In [42]:
vector = np.array([1,2,4,5,"Hola",True,52.3])
vector
#Cuando combinamos datos los convierte al dato mas generico

array(['1', '2', '4', '5', 'Hola', 'True', '52.3'], dtype='<U32')

In [44]:
#Copiar arrays
vector1=np.array([1,2,3,4])
vector1

array([1, 2, 3, 4])

In [46]:
vector2=vector1
vector2
#vector 2 es igual que vector 1 apuntan al mismo sitio 2840497220272 id(vector1)=id(vector2) es un alias de vector uno

array([1, 2, 3, 4])

In [48]:
id(vector1)

2840497220272

In [50]:
id(vector2)

2840497220272

In [57]:
#asi se copia y se crea otro vector y ocupa otro espacio
vector3=np.copy(vector1)
vector3
id(vector3)

2840497408784

In [1]:
#la copia ocupa espacio pero tengo un duplicado
#dos primeras horas con numpy  y ejercicios vamospor la pagina 50 


# Arrays multidimensionales, Matrices 31/10/2023
# h3 Diapositiva 50 Pag 25


In [4]:
li1=[[1,2,3],[4,5,6],[7,8,9]]
li1

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
#muestra el primer elemento fila 0 columna 0
li1[0][0]
#muestra el segundo elemento fila 0 columna 1
li1[0][1]


2

In [14]:
import numpy as np
#np.array(li1)
arr2d=np.array(li1)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
#Dimensión del array arr2d
arr2d.ndim


2

In [20]:
#Dimensión del array arr1d

arr1d=np.array([1,3,5,7,9])
arr1d.ndim

1

In [27]:
#array de arrays
arr3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [29]:
arr3d.ndim

3

In [31]:
#Matriz de 2x3 de 0 
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
#typo del primer elemento de la matriz
arr2dZero=np.zeros((2,3))
type(arr2dZero[0][0])

numpy.float64

In [38]:
#Puedo indicar el tipo de los datos de la  matriz
arr2dZero1=np.zeros((2,3), dtype='int64')
arr2dZero1


array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [40]:
type(arr2dZero1[0][0])

numpy.int64

# Propiedades de las matrices o arrays de dos o mas dimensiones Pag29 Dp57

In [45]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a.size #tamaño

9

In [49]:
a.shape #forma, Convertir la fila y las columnas en una tupla matriz de 3x3

(3, 3)

In [51]:
a.ndim

2

In [53]:
#para matrices unidimensionales (vectores), las tuplas devuelven el número de elementos
a1=np.array([2,5,1,3])
a1.shape

(4,)

In [55]:
#reformar cambiar de vector a matriz de dos dimensiones
a2=np.arange(15)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [59]:
a2.reshape((3,5)) #convierte el vector en un amatriz de 3x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#pag31 diapositiva 61
