In [1]:
import numpy as np

In [3]:
#Crear arrays 
# a partir de una lista
vector=np.array([1,2,3,4,5,6,7,8,9])
vector


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
type(vector)

numpy.ndarray

In [6]:
# a partir de una tupla
vector=np.array(["a","b","c"])
vector


array(['a', 'b', 'c'], dtype='<U1')

In [8]:
# a partir de unconjunto
vector=np.array({1,2,3,4,5,6,7,8,9})
vector

array({1, 2, 3, 4, 5, 6, 7, 8, 9}, dtype=object)

In [12]:
#con arrange
vector = np.arange(3, 10, 2)
vector


array([3, 5, 7, 9])

In [14]:
#rellenandocon 0 y 1
vector =np.zeros(7)
vector

array([0., 0., 0., 0., 0., 0., 0.])

In [17]:
vector = np.ones(4)
vector

array([1., 1., 1., 1.])

In [19]:
#con la funcion linspace()
# 5 valores entre uno y 10 repartidos con la misma distancia
vector = np. linspace(1,10,5)
vector



array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [21]:
#con la funcion linspace()
#5 valores entre  y 10 repartidos con la misma distancia
vector = np. linspace(0,100,5)
vector

array([  0.,  25.,  50.,  75., 100.])

In [27]:
#mezclando valores de tipos distintos
vector = np.array([1,2,3,4,5])
type(vector)
vector

array([1, 2, 3, 4, 5])

In [28]:
#al poner el 3.0 los convierte todos en flotante
vector = np.array([1,2,3.0,4,5])
type(vector)
vector

array([1., 2., 3., 4., 5.])

In [30]:
#al poner el false pone 0 que es el vlaorpor defecto de false
vector = np.array([1,2,4,5, False])
type(vector)
vector

array([1, 2, 4, 5, 0])

In [37]:
vector = np.array([1,2,4,1.05,5, False])

vector

array([1.  , 2.  , 4.  , 1.05, 5.  , 0.  ])

In [39]:
vector = np.array([1,2,4,5,"Hola"])
vector

array(['1', '2', '4', '5', 'Hola'], dtype='<U11')

In [42]:
vector = np.array([1,2,4,5,"Hola",True,52.3])
vector
#Cuando combinamos datos los convierte al dato mas generico

array(['1', '2', '4', '5', 'Hola', 'True', '52.3'], dtype='<U32')

In [32]:
#Copiar arrays
vector1=np.array([1,2,3,4])
vector1

array([1, 2, 3, 4])

In [33]:
vector2=vector1
vector2
#vector 2 es igual que vector 1 apuntan al mismo sitio 2840497220272 id(vector1)=id(vector2) es un alias de vector uno

array([1, 2, 3, 4])

In [34]:
id(vector1)

1582367794896

In [35]:
id(vector2)

1582367794896

In [36]:
#asi se copia y se crea otro vector y ocupa otro espacio
vector3=np.copy(vector1)
vector3
id(vector3)

1582367794704

In [37]:
vector1[0]=14
vector1

array([14,  2,  3,  4])

In [38]:
vector2

array([14,  2,  3,  4])

In [39]:
vector3[0]

1

In [40]:
#array multidimensional:matrices
lista = [1,2,3,4] # Creando Vectores y Matrices a raíz de listas
vector = np.array(lista)
vector

array([1, 2, 3, 4])

Ejercicios diapositivas

In [65]:
li1=[[1,2,3],[4,5,6],[7,8,9]]
li1


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [66]:
#muestra el primer elemento fila 0 columna 0
li1[0][0]
#muestra el segundo elemento fila 0 columna 1
li1[0][1]

2

In [67]:
import numpy as np
#np.array(li1)
arr2d=np.array(li1)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [68]:
#Dimensión del array arr2d
arr2d.ndim

2

In [69]:
#Dimensión del array arr1d

arr1d=np.array([1,3,5,7,9])
arr1d.ndim

1

In [70]:
#array de arrays
arr3d=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [71]:
arr3d.ndim

3

In [72]:
#Matriz de 2x3 de 0 
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [73]:
#typo del primer elemento de la matriz
arr2dZero=np.zeros((2,3))
type(arr2dZero[0][0])

numpy.float64

In [74]:
#Puedo indicar el tipo de los datos de la  matriz
arr2dZero1=np.zeros((2,3), dtype='int64')
arr2dZero1

array([[0, 0, 0],
       [0, 0, 0]], dtype=int64)

In [75]:
type(arr2dZero1[0][0])

numpy.int64

In [41]:
lista_de_listas = [[1,2,3],[4,5,6]]
lista_de_listas

[[1, 2, 3], [4, 5, 6]]

In [42]:
matriz = np.array(lista_de_listas)
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
lista_de_listas = [[1,2,3],[4,5,6,8]] # Error porque tiene un valor de más
lista_de_listas

[[1, 2, 3], [4, 5, 6, 8]]

In [44]:
matriz = np.array(lista_de_listas)
matriz # ValueError

C:\Users\CarmenM\AppData\Local\Temp\ipykernel_19880\3257633334.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  matriz = np.array(lista_de_listas)


array([list([1, 2, 3]), list([4, 5, 6, 8])], dtype=object)

In [45]:
matriz [1][1] # Accediendo a valores del vector


5

In [46]:
lista_de_listas[1][1] # Con listas solo funciona el doble corchete

5

In [48]:
matriz_3d = np.array([[[1,2],[3,4]],[[5,6], [7,8]]])# Matriz en 3d
matriz_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [49]:
matriz_3d[0,1,0] # Accediendo a valores de la matriz

3

In [50]:
vector.ndim # preguntamos por la dimensión del vector

1

In [51]:
matriz.ndim # preguntamos por la dimensión de la matriz

1

In [52]:
matriz = np.ones([5,3]) # Creando una matriz con 5 filas y 3 valores
matriz

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [53]:
matriz = np.ones([5,3], dtype="int32") # Pedirle que nos lo de en enteros
matriz

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [76]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
a.size #tamaño

9

In [78]:
a.shape #forma, Convertir la fila y las columnas en una tupla matriz de 3x3

(3, 3)

In [79]:
a.ndim


2

In [80]:
#para matrices unidimensionales (vectores), las tuplas devuelven el número de elementos
a1=np.array([2,5,1,3])
a1.shape

(4,)

In [81]:
#reformar cambiar de vector a matriz de dos dimensiones
a2=np.arange(15)
a2


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [82]:
a2.reshape((3,5)) #convierte el vector en un amatriz de 3x5

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [54]:
#propiedades
print(vector.size) # Consultar tamaño, columnas y/o filas, dimensiones
print(vector.shape)
print(vector.ndim)

4
(4,)
1


In [55]:
print(matriz.size)
print(matriz.shape)
print(matriz.ndim)

15
(5, 3)
2


In [57]:
#redimensionamiento
vector = np.array((7,5,6,4,3,2))
vector

array([7, 5, 6, 4, 3, 2])

In [58]:
matriz = vector.reshape(3,2) # Convertimos el vector en una matriz de 3 filas x 2 columnas
matriz

array([[7, 5],
       [6, 4],
       [3, 2]])

In [59]:
vector2 =  matriz2.reshape(6) # Recuperamos el vector
vector2

array([3, 2, 1, 6, 5, 4])

In [60]:
#añadir y borrar elementos de un array
vector = np.array(["blanco", "verde","azul", "amarillo"])
vector

array(['blanco', 'verde', 'azul', 'amarillo'], dtype='<U8')

In [61]:
vector2 = np.append(vector, ["naranja","negro"]) # Hacemos una copia para no pisar el anterior
vector2

array(['blanco', 'verde', 'azul', 'amarillo', 'naranja', 'negro'],
      dtype='<U8')

In [62]:
matriz = np.array([[1,2,3],[4,5,6]])
matriz

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
matriz2 = np.append(matriz,[[7,8,9]],axis=0)# Añadir una fila al final
matriz2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
matriz3 = np.append(matriz,[[7],[8]],axis=1)# Añadir una columa
matriz3

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

Operaciones con arrays y matrices


In [2]:
import numpy as np
matriz = np.random.rand(2,3)
matriz

array([[0.76328995, 0.47262705, 0.04407897],
       [0.53446086, 0.48638376, 0.18158606]])

In [3]:
#crea una matriz de numeros aleatorios siguiendo una distribucion normal con media 0 y desviacion estandar 1
matriz = np.random.randn(2,3)
matriz

array([[-1.61912301, -1.6226156 , -1.28384076],
       [-0.00876367, -2.12149455, -0.09622859]])

In [4]:
np.median(matriz)

-1.451481883829361

In [5]:
matriz = np.array([[1,2,3],[4,5,6]])
np.mean(matriz)

3.5

In [6]:
np.mean(matriz, axis=0)

array([2.5, 3.5, 4.5])

In [7]:
np.mean(matriz,axis=1)

array([2., 5.])

In [8]:
matriz1 = np.array([[1,2,3],[4,5,6]])
matriz2 = np.array([[3,2,1],[6,5,4]])



In [9]:
matriz1 + matriz2

array([[ 4,  4,  4],
       [10, 10, 10]])

In [10]:
matriz1-matriz2

array([[-2,  0,  2],
       [-2,  0,  2]])

In [11]:
matriz1 * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

In [12]:
print(matriz1)
matriz1 >2

[[1 2 3]
 [4 5 6]]


array([[False, False,  True],
       [ True,  True,  True]])

In [13]:
matriz1.sum(axis=1)

array([ 6, 15])

In [14]:
matriz1.min()

1

In [16]:
matriz1.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [17]:
matriz.min(axis=0)

array([1, 2, 3])

In [18]:
matriz.min(axis=1)

array([1, 4])

Acceso a apartes d euna matriz

In [20]:
vector  = np.array([1,2,3,4,5,6])
vector[3]

4

In [21]:
vector[:-1]

array([1, 2, 3, 4, 5])

In [24]:
matriz3 = np.array([[1,2,3,],[4,5,6],[3,5,6]])
matriz3


array([[1, 2, 3],
       [4, 5, 6],
       [3, 5, 6]])